_wandb:
    value:
        cli_version: 0.24.0
        e:
            84h920krcl9q9tohyno32venbfl0bhau:
                codePath: results/DistQuantum.py
                codePathLocal: results/DistQuantum.py
                cpu_count: 24
                cpu_count_logical: 32
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "1966736678912"
                        used: "1402779017216"
                email: a1174547806@gmail.com
                executable: /home/lizhao/miniconda3/envs/myenv/bin/python
                git:
                    commit: f70cc6889f09e6344dabbd8d78dc01f7df1eedb0
                    remote: https://github.com/Wlzzzz-del/DQC_Compiler.git
                gpu: NVIDIA GeForce RTX 5090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Blackwell
                      cudaCores: 21760
                      memoryTotal: "34190917632"
                      name: NVIDIA GeForce RTX 5090
                      uuid: GPU-a5c541b6-186f-8df3-1bc3-5397169f1e34
                host: PBWS1006639
                memory:
                    total: "134843219968"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/lizhao/CompilerDQC-main/results/DistQuantum.py
                python: CPython 3.10.19
                root: /home/lizhao/CompilerDQC-main
                startedAt: "2026-01-29T18:39:04.377332Z"
                writerId: 84h920krcl9q9tohyno32venbfl0bhau
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.10.19
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
feature:
    value: state_before_normalization
